In [1]:
## import numpy library
import numpy as np

## initialise array

In [7]:
# it will create 2*2 matrics of zeros
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [3]:
# it will create 2*2 matrics of 1
np.ones(  (2,2)   )

array([[1., 1.],
       [1., 1.]])

In [9]:
## to create 3 by 3 dignonal metrics
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
# [row, col] (2,2)
np.full((2,2), 45)

array([[45, 45],
       [45, 45]])

In [11]:
a = np.array([[1,2],[3,4]])
a.ndim 

# y = b0 + b1x1 + b2x2

2

In [7]:
np.full_like(a,4)

array([[4, 4],
       [4, 4]])

## Numpy Matrix

In python matrix() is returns a matrix from array or string of data.and given matrix is like specialised 2D array.

In [12]:
a = np.matrix('1 2; 3 4')
a

matrix([[1, 2],
        [3, 4]])

In [13]:
np.matrix([[1, 2], [3, 4]])

matrix([[1, 2],
        [3, 4]])

## Get elements / slicing

In [14]:
arr = np.array([[1,2,3,4,5,6], [5,6,7,8,8,1]])
print(arr)

[[1 2 3 4 5 6]
 [5 6 7 8 8 1]]


In [15]:
# get specific element [row,col]
arr[1,-1]

1

In [16]:
arr[1 , -4]

7

In [17]:
arr[0 , -2]

5

In [19]:
# get specific row 
arr[0 , :]

array([1, 2, 3, 4, 5, 6])

In [20]:
# get specific col
arr[: , 2]

array([3, 7])

In [22]:
arr

array([[1, 2, 3, 4, 5, 6],
       [5, 6, 7, 8, 8, 1]])

In [23]:
# [startindex:endindex] col -> n-1
arr[0 , 2:7]

array([3, 4, 5, 6])

In [16]:
# [startindex:endindex:stepsize]
arr[0, 1:6:2]

array([2, 4, 6])

In [24]:
arr[0, 1:-1:2]

array([2, 4])

In [18]:
arr

array([[1, 2, 3, 4, 5, 6],
       [5, 6, 7, 8, 8, 1]])

In [19]:
## Replace elements

In [27]:
arr[1,2] = 28
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 5,  6, 28,  8,  8,  1]])

### Random Number Generation
We can generate random number from discrete as well as continuos distributions.
- Continuos Distributions: beta,chisquare,log normal , standard exponential, parato distributions
- Discrete Distributions:  binomial, poisson ,unifrom,hypergeometric,geometric distributions

In [28]:
## random numbers [rows,col] -2 dimentional
ar2 = np.random.rand(4,2)
ar2

array([[0.86757119, 0.27530036],
       [0.758299  , 0.64805602],
       [0.52757615, 0.40520616],
       [0.96828025, 0.21441954]])

In [22]:
## random numbers  - 3 dimentional
ar2 = np.random.rand(2,2,3)
ar2

array([[[0.23360358, 0.70602319, 0.22319167],
        [0.32322318, 0.77466638, 0.04828038]],

       [[0.79081537, 0.93827205, 0.9855421 ],
        [0.37993814, 0.40442929, 0.6297102 ]]])

In [23]:
## Ex of randit function
ar3 = np.random.randint(4,7)
ar3

6

In [24]:
ar3 = np.random.randint(4 , size=(2,2))
ar3

array([[2, 3],
       [2, 1]])

In [29]:
# repeate the arrary
ar3 = np.array([1,2,3])
ar3 = np.repeat(ar3, 2, axis=0)
ar3

array([1, 1, 2, 2, 3, 3])

In [26]:
## generating random number from normal distribution
# random numbers mean=5 and sd=.2.
num1 = np.random.normal(5, .2, 10)   
num1

array([5.44513071, 5.04406614, 5.00877385, 4.83456297, 5.21903374,
       5.19287107, 4.9251588 , 4.7487548 , 5.31527478, 4.82763251])

In [27]:
# Ex.2 of generating random number from Standard normal distribution
num1 = np.random.normal(0, 1, 10)   
num1

array([-1.9275956 ,  0.74586276, -0.19448973,  0.65551107, -0.39347043,
        1.14439479, -0.67366424, -1.23844885,  0.78325492, -0.09419571])

In [28]:
## generating random number from Exponential distribution
num2 = np.random.exponential(5,10)
num2

array([3.42274804e-01, 7.78740522e+00, 3.18934194e-01, 3.60675862e-01,
       3.10691326e+00, 1.05050586e+00, 8.17917134e+00, 2.04486916e-03,
       5.44636878e+00, 5.88855331e+00])

In [32]:
## generating random number from Possion distribution
num3 = np.random.poisson(3,10)
num3

array([7, 2, 5, 3, 2, 2, 4, 3, 2, 3])

In [30]:
## to shuffle the array
array = np.array([1,2,3,4,5,6,7,8])
np.random.shuffle(array)
print(array)

[6 1 3 5 2 4 7 8]


### Maths

In [31]:
## To calculate mean
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [32]:
a+2

array([3, 4, 5, 6, 7])

In [33]:
a-1

array([0, 1, 2, 3, 4])

In [34]:
a*4

array([ 4,  8, 12, 16, 20])

In [35]:
b = np.array([1,2,3,4,5])
b

array([1, 2, 3, 4, 5])

In [36]:
a+b

array([ 2,  4,  6,  8, 10])

## Statistics

In [37]:
## To calculate mean/average
array = np.array([1,2,3,4,5,6,7,8])
array.mean()

4.5

In [38]:
## Ex. of mean
array1 = np.random.normal(5,0.8,20)
array1.mean()

4.939108041343774

In [39]:
array = np.array([1,2,3,4,5,6,7,8])
array.std()

2.29128784747792

In [40]:
## Ex. of sd
array1 = np.random.normal(5,0.8,20)
array1.std()

0.7138304765023525

In [41]:
## Here we Create another array for perform some operations.
ar1 = np.array([23,7,3,14,5,66,2,8,9])
ar1 = ar1.reshape(3,3)
ar1

array([[23,  7,  3],
       [14,  5, 66],
       [ 2,  8,  9]])

In [42]:
## to calculate max. value 
ar1.max()

66

In [43]:
## to calculate min.value
ar1.min()

2

In [44]:
# to find index position where it has max. value
ar1.argmax()

5

In [45]:
# to find index position where it has min. value
ar1.argmin()

6

Round function:
The ROUND function is used to return a number rounded to a specific number of digits

In [46]:
## The ROUND function 
np.round(234.6789,2)

234.68

Power function:  Power function is used to calculate the power raised to the base value

In [47]:
## to calculte power of specific number
np.power(2,3)

8

In [48]:
## it will calculate the absolute value of every value in the array.
np.abs(-20)

20

In [49]:
## to calculate returns the arithmetic mean of elements in the array
np.mean(0)

0.0

In [50]:
## to calculate Natural logarithm of input array elements
np.log(5)

1.6094379124341003

In [51]:
## to calculate a square of element
np.square(5)

25

In [52]:
## to calculate a squareroot of perticular element
np.sqrt(9)

3.0

## Linear algrebra

In [53]:
 # 2X3
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [54]:
# 3X2
b = np.full((3,2), 5)
b

array([[5, 5],
       [5, 5],
       [5, 5]])

In [55]:
# 2X3 , 3X2 --> 2X2
np.matmul(a,b)

array([[15., 15.],
       [15., 15.]])

## references

1. create or inititialise array: https://numpy.org/doc/stable/reference/routines.array-creation.html
2. mathematical functions: https://numpy.org/doc/stable/reference/routines.math.html
3. linear algebra: https://numpy.org/doc/stable/reference/routines.linalg.html

## Math Library
  Math Library provides us access to some common math functions and constants in Python

In [56]:
## import Math library
import math  

In [57]:
##  to calculate the factorial of a given number it accepts only positive number and return the factorial of number.
math.factorial(5) 

120

In [58]:
## to calculate the power of e
math.exp(5)

148.4131591025766